Repository matchai/spacefish, pull requests merged in 2018-12, with the labels that each got.

#122 Hide kubecontext outside of kube project
  fish_mode_prompt.fish
  functions/__sf_section_kubecontext.fish
  tests/__sf_section_conda.test.fish
  tests/__sf_section_docker.test.fish
  tests/__sf_section_host.test.fish
  tests/__sf_section_kubecontext.test.fish
  tests/__sf_util_git_branch.test.fish
Labels: Type: Bug

#120 Add tests for git status section
  functions/__sf_section_conda.fish
  functions/__sf_section_docker.fish
  functions/__sf_section_git_status.fish
  tests/__sf_section_aws.test.fish
  tests/__sf_section_conda.test.fish
  tests/__sf_section_dir.test.fish
  tests/__sf_section_docker.test.fish
  tests/__sf_section_exit_code.test.fish
  tests/__sf_section_git_status.test.fish
  tests/__sf_section_golang.test.fish
  tests/__sf_section_host.test.fish
  tests/__sf_section_jobs.test.fish
  tests/__sf_section_julia.test.fish
  tests/__sf_section_kubecontext.test.fish
  tests/__sf_section_node.test.fish
  tests/__sf_section_php.test.fish
  tests/__sf_section_pyenv.test.fish
  tests/__sf_section_rust.test.fish
  tests/__sf_section_time.test.fish
  tests/__sf_section_vi_mode.test.fish
  tests/__sf_util_git_branch.test.fish
  tests/mock.fish
  tests/run.fish
  tests/spacefish_test_setup.fish
Labels: Type: Maintenance

#83 Dotnet section
  README.md
  docs/Options.md
  docs/README.md
  fish_prompt.fish
  functions/__sf_section_dotnet.fish
  tests/__sf_section_dotnet.test.fish
Labels: Type: Enhancement

#125 Automate project versioning with semantic-release
  .travis.yml
  package-lock.json
  package.json
  scripts/version.fish
Labels: Type: Maintenance
