Repository matchai/spacefish, pull requests merged in 2019-02, with the labels that each got.

#145 Improve dotnet project detection
  docs/Options.md
  functions/__sf_section_dotnet.fish
  tests/__sf_section_dotnet.test.fish
Labels: Type: Enhancement

#152 ci: lock the fishtape test dependency to v1
  tests/run.fish
Labels: Type: Maintenance

#156 Use provided format via SPACEFISH_TIME_FORMAT
  functions/__sf_section_time.fish
Labels: Type: Bug

#155 SPACEFISH_GIT_STATUS_SHOW is never checked
  functions/__sf_section_git_status.fish
  tests/__sf_section_git_status.test.fish
Labels: Type: Bug

#160 docs: update supported fish to v3.0.2
  README.md
Labels: Type: Maintenance
